"""Stabile Aktionskennungen, Gruppen und Editorbefehle ohne Tk.

LEGACY_GROUPS bewahrt nur den alten Abfragevertrag der Pruefwerkzeuge.
Menue und Palette ordnen und dispatchen ausschliesslich nach Aktions-ID.
"""
GROUP_ORDER = ('Neu anlegen',
 'Import',
 'Export',
 'Bearbeiten',
 'Struktur und Gliederung',
 'Planen und einordnen',
 'Ansichten',
 'Ansichtseinstellungen',
 'Daten und Ablage',
 'Programm und Hilfe',
 'Weitere Aktionen')

GROUPS = {
    "show_object_references": "Ansichten",'show_library_new_menu': 'Neu anlegen', 'show_library_import_menu': 'Import', 'toggle_view_hints': 'Ansichtseinstellungen', 'show_tasks_from_pages': 'Ansichten','show_quick_plan_menu': 'Planen und einordnen',
'skip_repeat_selected': 'Planen und einordnen',
'add_item_advanced': 'Neu anlegen',
'skip_missed_repeats_selected': 'Planen und einordnen',
'start_day_proposal': 'Planen und einordnen',
'start_focus_selected': 'Planen und einordnen',
'choose_time_block': 'Planen und einordnen',
'collapse_all': 'Struktur und Gliederung',
 'convert_selected_kind.group': 'Struktur und Gliederung',
 'convert_selected_kind.task': 'Struktur und Gliederung',
 'copy_selected_to_clipboard': 'Bearbeiten',
 'create_new_drawing': 'Neu anlegen',
 'create_new_folder': 'Neu anlegen',
 'create_new_gallery': 'Neu anlegen',
 'create_new_list': 'Neu anlegen',
 'create_new_page': 'Neu anlegen',
 'cycle_importance_selected': 'Planen und einordnen',
 'data_directory.show': 'Daten und Ablage',
 'delete_item': 'Bearbeiten',
 'dissolve_selected_group': 'Struktur und Gliederung',
 'duplicate_selected_items': 'Bearbeiten',
 'edit_item': 'Bearbeiten',
 'edit_page_note': 'Bearbeiten',
 'empty_trash': 'Bearbeiten',
 'expand_all': 'Struktur und Gliederung',
 'export_app_backup': 'Export',
 'export_as_csv': 'Export',
 'export_as_markdown': 'Export',
 'export_as_txt': 'Export',
 'export_full_backup': 'Export',
 'export_glide_pages': 'Export',
 'export_templates_file': 'Export',
 'group_selected_items': 'Struktur und Gliederung',
 'import_drawing_as_new': 'Import',
 'import_from_txt': 'Import',
 'import_full_backup': 'Import',
 'import_glide_pages': 'Import',
 'import_markdown_page': 'Import',
 'import_partial_backup': 'Import',
 'import_templates_file': 'Import',
 'import_txt_as_new_lists': 'Import',
 'move_selected_to_list_dialog': 'Bearbeiten',
 'new_page_from_clipboard': 'Import',
 'on_close': 'Programm und Hilfe',
 'open_backup_folder': 'Daten und Ablage',
 'show_backup_compare_dialog': 'Daten und Ablage',
 'open_board_view': 'Ansichten',
 'open_calendar_view': 'Planen und einordnen',
 'open_error_log': 'Programm und Hilfe',
 'open_global_board': 'Ansichten',
 'open_history_view': 'Daten und Ablage',
 'open_inbox_list': 'Ansichten',
 'open_label_manager': 'Planen und einordnen',
 'open_list_view': 'Ansichten',
 'open_next_task': 'Ansichten',
 'open_reminders': 'Planen und einordnen',
 'paste_items_from_clipboard': 'Bearbeiten',
 'plan_day_backward': 'Ansichten',
 'plan_day_forward': 'Ansichten',
 'remove_done_items': 'Bearbeiten',
 'restore_app_backup': 'Import',
 'select_all_items': 'Bearbeiten',
 'set_due_date_selected': 'Planen und einordnen',
 'set_home_view': 'Ansichten',
 'set_in_progress_view': 'Ansichten',
 'set_overdue_view': 'Ansichten',
 'set_planning_selected': 'Planen und einordnen',
 'set_table_nested.false': 'Ansichtseinstellungen',
 'set_table_nested.true': 'Ansichtseinstellungen',
 'set_table_view': 'Ansichten',
 'set_template_view': 'Ansichten',
 'set_today_view': 'Ansichten',
 'set_trash_view': 'Ansichten',
 'show_about_dialog': 'Programm und Hilfe',
 'show_calendar_export_dialog': 'Export',
 'show_csv_import_dialog': 'Import',
 'show_data_folder_dialog': 'Daten und Ablage',
 'show_exchange_export_dialog': 'Export',
 'show_exchange_import_dialog': 'Import',
 'show_exchange_spec_dialog': 'Programm und Hilfe',
 'show_home_tiles_dialog': 'Ansichten',
 'show_ics_import_dialog': 'Import',
 'show_manager': 'Ansichten',
 'show_manual_dialog': 'Programm und Hilfe',
 'show_print_dialog': 'Export',
 'show_quick_capture': 'Neu anlegen',
 'show_quick_open': 'Ansichten',
 'show_settings_dialog': 'Ansichtseinstellungen',
 'show_shortcuts_dialog': 'Programm und Hilfe',
 'show_table_columns_dialog': 'Ansichtseinstellungen',
 'show_week_review': 'Ansichten',
 'sort_current_list.alpha': 'Struktur und Gliederung',
 'sort_current_list.due': 'Struktur und Gliederung',
 'sort_current_list.importance': 'Struktur und Gliederung',
 'start_day_close': 'Ansichten',
 'start_day_review': 'Ansichten',
 'test_system_notification': 'Planen und einordnen',
 'toggle_detail_pane': 'Ansichtseinstellungen',
 'toggle_plan_day_grid': 'Ansichten',
 'toggle_sidebar': 'Ansichtseinstellungen',
 'toggle_sidebar_narrow': 'Ansichtseinstellungen',
 'explain_saved_filter': 'Ansichten',
 'toggle_theme': 'Ansichtseinstellungen',
 'undo_last_change': 'Bearbeiten',
 'use_default_data_folder': 'Daten und Ablage',
 'workspace.close_tab': 'Ansichten',
 'workspace.open_tab': 'Ansichten',
 'workspace.pin': 'Ansichten',
 'workspace.reorder_tab.-1': 'Ansichten',
 'workspace.reorder_tab.1': 'Ansichten',
 'workspace.tab_overview': 'Ansichten'}

LEGACY_GROUPS = {'show_library_new_menu': 'Neu anlegen', 'show_library_import_menu': 'Import', 'toggle_view_hints': 'Ansichtseinstellungen', 'show_tasks_from_pages': 'Ansichten','Einplanen': 'Planen und einordnen', 'Diesen Termin überspringen': 'Planen und einordnen', 'Verpasste Termine überspringen': 'Planen und einordnen',
'Alle auswählen': 'Bearbeiten',
 'Alphabetisch': 'Struktur und Gliederung',
 'Als CSV …': 'Export',
 'Als Glide-Seite …': 'Export',
 'Als Markdown …': 'Export',
 'Als Reiter öffnen': 'Ansichten',
 'Als TXT …': 'Export',
 'App-Backup wiederherstellen …': 'Import',
 'Auf Pinnwand anheften': 'Ansichten',
 'Aufklappen': 'Struktur und Gliederung',
 'Austauschformat anzeigen …': 'Programm und Hilfe',
 'Auswahl gruppieren …': 'Struktur und Gliederung',
 'Backup-Ordner öffnen': 'Daten und Ablage',
 'Bearbeitungstag und Aufwand …': 'Planen und einordnen',
 'Beenden': 'Programm und Hilfe',
 'Benachrichtigungen …': 'Planen und einordnen',
 'CSV importieren …': 'Import',
 'Datenordner wechseln …': 'Daten und Ablage',
 'Demnächst': 'Ansichten',
 'Design wechseln (Hell/Dunkel)': 'Ansichtseinstellungen',
 'Detailbereich ein-/ausblenden': 'Ansichtseinstellungen',
 'Drucken und PDF …': 'Export',
 'Duplizieren': 'Bearbeiten',
 'Einfügen': 'Bearbeiten',
 'Eingang öffnen': 'Ansichten',
 'Einstellungen …': 'Ansichtseinstellungen',
 'Erledigte Punkte löschen': 'Bearbeiten',
 'Fehlerprotokoll öffnen': 'Programm und Hilfe',
 'Fälligkeitsdatum …': 'Planen und einordnen',
 'Für KI bereitstellen …': 'Export',
 'Gespeicherte Filter …': 'Ansichten',
 'Glide-Seiten importieren …': 'Import',
 'Globale Pinnwand öffnen': 'Ansichten',
 'Gruppe auflösen': 'Struktur und Gliederung',
 'Gruppieren: Bearbeitungstag': 'Ansichtseinstellungen',
 'Gruppieren: Dringlichkeit × Wichtigkeit': 'Ansichtseinstellungen',
 'Gruppieren: Erledigt': 'Ansichtseinstellungen',
 'Gruppieren: Fälligkeit': 'Ansichtseinstellungen',
 'Gruppieren: Label': 'Ansichtseinstellungen',
 'Gruppieren: Wichtigkeit': 'Ansichtseinstellungen',
 'Gruppieren: aus': 'Ansichtseinstellungen',
 'Handbuch …': 'Programm und Hilfe',
 'Heute': 'Ansichten',
 'Heute: Stundenraster ein/aus': 'Ansichten',
 'Heute: Tag vor': 'Ansichten',
 'Heute: Tag zurück': 'Ansichten',
 'In Aufgabe zurückwandeln': 'Struktur und Gliederung',
 'In Gruppe umwandeln': 'Struktur und Gliederung',
 'In Liste verschieben …': 'Bearbeiten',
 'KI-Ergebnis importieren …': 'Import',
 'Kalender …': 'Planen und einordnen',
 'Kalenderdatei (ICS) importieren …': 'Import',
 'Kalenderdatei (ICS) …': 'Export',
 'Komplettbackup laden …': 'Import',
 'Komplettbackup speichern …': 'Export',
 'Kopieren': 'Bearbeiten',
 'Labels verwalten …': 'Planen und einordnen',
 'Listen/Ordner hinzufügen …': 'Import',
 'Löschen': 'Bearbeiten',
 'Markdown als Seite …': 'Import',
 'Nach Fälligkeit': 'Struktur und Gliederung',
 'Nach Wichtigkeit': 'Struktur und Gliederung',
 'Neue Galerie': 'Neu anlegen',
 'Neue Liste': 'Neu anlegen',
 'Neue Seite': 'Neu anlegen',
 'Neue Zeichnung': 'Neu anlegen',
 'Neuer Ordner': 'Neu anlegen',
 'Nächste Aufgabe': 'Ansichten',
 'Offene Reiter …': 'Ansichten',
 'Papierkorb': 'Ansichten',
 'Papierkorb leeren': 'Daten und Ablage',
 'Pinnwand öffnen': 'Ansichten',
 'Punktdetails …': 'Bearbeiten',
 'Reiter nach links': 'Ansichten',
 'Reiter nach rechts': 'Ansichten',
 'Reiter schließen': 'Ansichten',
 'Rückgängig': 'Bearbeiten',
 'Schnellerfassung …': 'Neu anlegen',
 'Seite aus Zwischenablage': 'Import',
 'Seite, Punkt oder Aktion suchen …': 'Ansichten',
 'Seitenleiste ein-/ausblenden': 'Ansichtseinstellungen',
 'Standardordner benutzen': 'Daten und Ablage',
 'Startseite': 'Ansichten',
 'Startseite einrichten …': 'Ansichten',
 'Systemmitteilung testen': 'Planen und einordnen',
 'TXT als neue Liste(n) …': 'Import',
 'TXT importieren …': 'Import',
 'Tabelle: Unterpunkte flach': 'Ansichtseinstellungen',
 'Tabelle: Unterpunkte verschachtelt': 'Ansichtseinstellungen',
 'Tabellenansicht': 'Ansichten',
 'Tabellenspalten …': 'Ansichtseinstellungen',
 'Tagesabschluss …': 'Ansichten',
 'Tagesbeginn …': 'Ansichten',
 'Tastenkürzel anzeigen': 'Programm und Hilfe',
 'Titel und Beschreibungstext …': 'Bearbeiten',
 'Verspätet': 'Ansichten',
 'Vollständiges App-Backup speichern …': 'Export',
 'Vorlagen': 'Ansichten',
 'Vorlagen exportieren …': 'Export',
 'Vorlagen hinzufügen …': 'Import',
 'Vorlagen öffnen': 'Ansichten',
 'Wichtigkeit ändern': 'Planen und einordnen',
 'Wo liegen meine Daten?': 'Daten und Ablage',
 'Wochenrückblick': 'Ansichten',
 'Zeichnung (SVG/JSON) importieren …': 'Import',
 'Zuklappen': 'Struktur und Gliederung',
 'Zur Listenansicht': 'Ansichten',
 'Änderungsverlauf': 'Daten und Ablage'}

EDITOR_EVENTS = {
    "copy_selected_to_clipboard": "<<Copy>>", "paste_items_from_clipboard": "<<Paste>>",
    "undo_last_change": "<<Undo>>", "select_all_items": "<<SelectAll>>",
}


def method_id(callback):
    value = getattr(callback, "__name__", "")
    if not value or value == "<lambda>":
        raise ValueError("Anonyme Aktionen brauchen eine explizite Kennung")
    return value


def group_for(action_id):
    if action_id.startswith(("backdrop.", "grouping.")):
        return "Ansichtseinstellungen"
    return GROUPS.get(action_id, "Weitere Aktionen")


def legacy_group(label):
    if label.startswith("Über "):
        return "Programm und Hilfe"
    if label.startswith("Hintergrund: "):
        return "Ansichtseinstellungen"
    return LEGACY_GROUPS.get(label, "Weitere Aktionen")


def editor_event(action_id):
    return EDITOR_EVENTS.get(action_id)


def legacy_groups():
    """Bisherige Gruppentabelle als abgeleitete Kompatibilitätsansicht."""
    return {group: tuple(label for label, assigned in LEGACY_GROUPS.items() if assigned == group)
            for group in GROUP_ORDER if group != "Weitere Aktionen"}
